ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0-beta.1
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.8.3"]
